Fix: Empty task list, Fixes #14
selfire1/todoist-focus-mode pull request #18
Opened 2024-11-29 09:29 UTC by ronilaukkarinen

This makes the filters show up again. 👍 
I also added a CHANGELOG and debug logging in dev.

2024-11-30 02:14 UTC, selfire1 requested changes
Thank you!

Only change request is to use `[import.meta.dev](https://nuxt.com/docs/api/advanced/import-meta#runtime-app-properties)`. It is the [recommended method](https://github.com/nuxt/nuxt/discussions/18779#discussioncomment-8864742) to check if Nuxt is in development mode.

2024-11-30 02:14 UTC, selfire1 commented on src/pages/secure/index.vue
> +    if (process.dev) {
```suggestion
    if (import.meta.dev) {
```

2024-11-30 02:14 UTC, selfire1 commented on src/pages/secure/index.vue
> +  if (process.dev) {
```suggestion
  if (import.meta.dev) {
```

2024-11-30 02:14 UTC, selfire1 commented on src/pages/secure/index.vue
> +if (process.dev) {
```suggestion
if (import.meta.dev) {
```

2024-12-02 08:14 UTC, ronilaukkarinen commented
OK, this whole stack and Nuxt is very new to me 😅 I'll check it out and fix soon.

2024-12-04 01:55 UTC, selfire1 approved these changes

2024-12-04 01:56 UTC, merged